### ISSUE TITLE
When user logs in parsecalendar in calbox and home doesn't run readData

### ISSUE THREAD

**Issue by Sharqosity** [s0urc3d3v3l0pm3nt/whs_planner#102]

**Comment by Sharqosity** [comment]
@Vrend John is there any way to check if the user is logged in with the Schedule class?

**Comment by Vrend** [comment]
check if the json file exists

**Comment by Sharqosity** [comment]
No, the json file can exist while the user is logged out. For example, after they click the logout button. But the method that's supposed to delete the file doesn't...
