### ISSUE TITLE
text field request focus - doesn't work when you unselected and reselect an already created calendarbox

### ISSUE THREAD

**Issue by Sharqosity** [s0urc3d3v3l0pm3nt/whs_planner#106]
when you click on a new calendar box, the request focus on the text field works. But when you deselect and then reselect that calendar box, it won't focus on the text box anymore.

**Comment by s0urc3d3v3l0pm3nt** [comment]
why is this a "won't fix"

**Comment by Sharqosity** [comment]
Tyler on Discord: 
"that's not really something I can fix...
callFocus is known as a fairly glitchy function...
I can try it...
but
I doubt anything will work"
