### ISSUE TITLE
Please merge with packages and create a new branch

### ISSUE THREAD

**Issue by s0urc3d3v3l0pm3nt** [s0urc3d3v3l0pm3nt/whs_planner#11]
You must have the new .travis.yml file in your root directory to be compatable with some new changes

**Comment by Sharqosity** [comment]
Is this why some branches are 1.1/1.2 now?

**Comment by TheCynosure** [comment]
@Sharqosity if you did not merge your branch with Packages yet then delete your 1.2 branch, merge your branch, and create a new 1.2 branch. As the 1.2 branch for you might not be up to date with packages / your 1.1 branch.
Just in case Melbing already merged the branches we should ask first, @s0urc3d3v3l0pm3nt.

**Comment by s0urc3d3v3l0pm3nt** [comment]
Their where significant changes to the packages branch which should be included on all other branches so please make a new branch for your team
