### ISSUE TITLE
Get Sports data from pop-up

### ISSUE THREAD

**Issue by s0urc3d3v3l0pm3nt** [s0urc3d3v3l0pm3nt/whs_planner#16]
Could the core UI team build a pop-up that asked for sports times so that they could be passed to the sports group through core who can do the  data management and storage.

**Comment by andreweggleston** [comment]
@TBrient we have a controller and fxml for the popup, can you just make the fxml look nice and i can make the methods?

**Comment by TBrient** [comment]
ye
