### ISSUE TITLE
The News Merge

### ISSUE THREAD

**Issue by Sharqosity** [s0urc3d3v3l0pm3nt/whs_planner#34]
I think that News_Edgy-v2 is coming well enough that it's time to merge with MainUI. However, 2 possible issues:
It's using the jfoenix jar instead of maven jfoenix
The travis build doesn't pass for some reason

**Comment by andreweggleston** [comment]
We should all be using maven for library management. Just add the library from maven and get rid of the jar.

**Comment by Sharqosity** [comment]
It doesn't work without the jar. Me and geoffrey literally spent like 5 days making it work and it needed the jar

**Comment by andreweggleston** [comment]
WutFace

**Comment by andreweggleston** [comment]
Turns out its just an issue with the current build of JFoenix thats on Maven, unless the version there is updated, you need to continue using the jar provided on [the JFoenix github](https://github.com/jfoenixadmin/JFoenix). Just merge and let tyler take care of it.

**Comment by Sharqosity** [comment]
Apparently the current version is still 1.0.0, idk I'll merge and blame all problems on Tyler
