### ISSUE TITLE
sidebar needs a shadow

### ISSUE THREAD

**Issue by s0urc3d3v3l0pm3nt** [s0urc3d3v3l0pm3nt/whs_planner#47]
There is no shadow under the sidebar which makes it look weird and does not conform to google's design standards (Material)

**Comment by Sharqosity** [comment]
Issue: I gave both the top bar and the sidebar shadows, but the sidebar technically draws over the top bar. This should be the other way around so the top bar shadow shows on the top of the sidebar.
![screen shot 2016-12-05 at 2 47 47 pm](https://cloud.githubusercontent.com/assets/15043338/20899794/e521bcea-baf9-11e6-819c-3db6f1368b95.png)

**Comment by Sharqosity** [comment]
More or less fixed.
