### ISSUE TITLE
If you click on an empty spot in the side bar, the hamburger animation plays again

### ISSUE THREAD

**Issue by Sharqosity** [s0urc3d3v3l0pm3nt/whs_planner#48]
The animation resets to the 3 lines then goes to the arrow. Try it yourself

**Comment by Razer0901** [comment]
Again, this is core UI... If it isn't code breaking, I'm not going to fix
it... At least for now...

**Comment by TBrient** [comment]
Okay I'll fix it

**Comment by andreweggleston** [comment]
i already FIXED IT smh 👯

**Comment by andreweggleston** [comment]
just kidding

**Comment by TBrient** [comment]
I fixed it. I'm good at coding. I'm not gonna do anything now
