### ISSUE TITLE
First click doesn't register after side bar closes

### ISSUE THREAD

**Issue by Sharqosity** [s0urc3d3v3l0pm3nt/whs_planner#49]
Happens in all tabs, news tab needs 2 clicks to show scroll bar as well.

**Comment by Razer0901** [comment]
Wait... Why am I be assigned to all of these? They are core ui stuff which
I am not part of, I just helped rewrite broken code...

**Comment by s0urc3d3v3l0pm3nt** [comment]
Sry, forgot you where not part of UI

**Comment by Sharqosity** [comment]
fixed 💯 💯 💯 💯 💯 💯 💯
