### ISSUE TITLE
Calendar: Ripple effect slightly misplaced upon selection

### ISSUE THREAD

**Issue by Sharqosity** [s0urc3d3v3l0pm3nt/whs_planner#51]
When you select a calendar box, all the boxes in that row become slightly shorter, but the ripple animation fills to the size it was before.

When you deselect it, the boxes return to normal height but the ripple animation only fills that of the reduced height.

**Comment by Razer0901** [comment]
Tried fixing a while back, could be a jfoneix bug...

**Comment by Sharqosity** [comment]
You could go back to the thing where it just moves the boxes down when you select, and leave a little extra space at the bottom.

**Comment by Razer0901** [comment]
It isn't selecting, the real problem is within the scaling. It doesn't scale no matter how you do it. (Properly) Might be possible if you recreated ripplers every time the screen scales.
