### ISSUE TITLE
Calendar should highlight current day

### ISSUE THREAD

**Issue by Sharqosity** [s0urc3d3v3l0pm3nt/whs_planner#55]

**Comment by TBrient** [comment]
What color should we highlight it in?

**Comment by Sharqosity** [comment]
Orange or a lighter gray maybe

**Comment by TBrient** [comment]
Papa bless, now the number highlights for today in orange (you'll see). It should work once the dates get sorted out. 😽

**Comment by Sharqosity** [comment]
Papa bless tyler
