### ISSUE TITLE
Schedule: Add a method to get the progress bar ONLY, as a pane

### ISSUE THREAD

**Issue by Sharqosity** [s0urc3d3v3l0pm3nt/whs_planner#56]
I need it for muh home screen

**Comment by Razer0901** [comment]
Please specify which progress bar, also doesn't having a function with the data work, does it have to specifically be the pane?

**Comment by Sharqosity** [comment]
I don't know lmao because I can't log into schedule, it's the bar telling you how far you are into the period. Yes, data also works.

**Comment by Sharqosity** [comment]
nvm I figured it out, issue resolved.
