### ISSUE TITLE
Calendar: Interaction with day boxes causes them to get taller

### ISSUE THREAD

**Issue by TheCynosure** [s0urc3d3v3l0pm3nt/whs_planner#60]
For some reason clicking on the current calendar day and typing seems to push the text box down the screen more.

**Comment by Sharqosity** [comment]
@Razer0901 Couldn't we revert Calendar back to a borderpane without any problems? What is your plan with ContentPane?

**Comment by Sharqosity** [comment]
Issue resolved.
