### ISSUE TITLE
Calendar: Bottom row events will go offscreen

### ISSUE THREAD

**Issue by Sharqosity** [s0urc3d3v3l0pm3nt/whs_planner#63]
Once the calendar snaps to all the edges, there's a problem if you add too many assignments to the bottom row of the month. They literally won't be visible.
The events added to the last week of the month will go offscreen until the window is resized to be higher. Screenshot: 
![screen shot 2016-12-13 at 10 31 13 pm](https://cloud.githubusercontent.com/assets/15043338/21168671/fdd84f5c-c183-11e6-9c0a-78df42c4fb1e.png)
It pushes the progress bar down too.
_Maybe_ have the events in a scrollpane?

**Comment by s0urc3d3v3l0pm3nt** [comment]
This issue is very ambiguous.  maybe a more descriptive title.

**Comment by Sharqosity** [comment]
Currently there is an issue where calendar remains the same size when the window resizes. Once this bug is fixed, the issue in question should be addressed

**Comment by Sharqosity** [comment]
The events added to the last week of the month will go offscreen until the window is resized to be higher. Screenshot: 
![screen shot 2016-12-13 at 10 31 13 pm](https://cloud.githubusercontent.com/assets/15043338/21168671/fdd84f5c-c183-11e6-9c0a-78df42c4fb1e.png)
It pushes the progress bar down too.
_Maybe_ have the events in a scrollpane?
