### ISSUE TITLE
Calendar: Current day highlight only shows on first week

### ISSUE THREAD

**Issue by Sharqosity** [s0urc3d3v3l0pm3nt/whs_planner#64]
Last thursday it was working fine because it was the 1st thursday of the month, but now today is the **2nd** Monday of the month and the highlight is on the 1st Monday of the month.

**Comment by TBrient** [comment]
Someone retarded made the "date" variable the day of the current week... Not my fault... (The date variable is commented as "This box's date." To quote Dumais, "Like really tho?" 😽

**Comment by TBrient** [comment]
Praise the lord I'm not fei chang stupid 😽

**Comment by Sharqosity** [comment]
NIS
