### ISSUE TITLE
Create UI for error from ErrorHandler 

### ISSUE THREAD

**Issue by s0urc3d3v3l0pm3nt** [s0urc3d3v3l0pm3nt/whs_planner#7]
The error handler class allows you to call an error without having to recreate one every time you need to catch something but the core-ui group will have to create an error pop up for it

**Comment by s0urc3d3v3l0pm3nt** [comment]
The ErrorHandler class has been pushed to master and can be cherrypicked with the Version Control tab then selecting the core merge with master and cherrypicking it

**Comment by Razer0901** [comment]
If I'm not mistaken to which error this is (loading FXML causes error), apparently it can be solved by creating a resources folder and placing the FXML file in there. I have it working in the Calendar Branch, if anyone wants to rebase to that to check it out. I changed the structure of the file folders, so I do not want to merge to master.

If this is not about that error, I'll delete this message!

-Geoffrey Wang

**Comment by s0urc3d3v3l0pm3nt** [comment]
I was more wondering if we could make a pop up that displayed an error message ie displayError(String msg).

**Comment by Razer0901** [comment]
Ah, ok my bad! Basically, you want to have the error pop up instead of in the logs. I think you will have to teach us how to cherrypick in intellj and how to use the ErrorHandler class in class.

-Geoffrey Wang
P.S. Who are you? Matt?

**Comment by andreweggleston** [comment]
@Razer0901 yeah that's Matt. What he wants Tyler and I to do is to create a little popup that appears whenever there's an error. Something along the lines of 
`listener.listenFor(error)`, then create a window with information from the `error` object.

**Comment by s0urc3d3v3l0pm3nt** [comment]
@andreweggleston This is perfect I currently have the methods:

- handleGenericError()
- HandleIOError()
- handleThreadError()

**Comment by s0urc3d3v3l0pm3nt** [comment]
Danke für dies hilfe!
