### ISSUE TITLE
UI: Schedule progress bar needs decision made

### ISSUE THREAD

**Issue by Vrend** [s0urc3d3v3l0pm3nt/whs_planner#73]
When you login to ipass, the progress bar is shown

When you close and open the app up it will be gone

Make up your mind George

**Comment by Sharqosity** [comment]
This is just a side-effect of my shitty code. I literally don't know why it steals it from the schedule tab, it should show in both

**Comment by Vrend** [comment]
then fix it

**Comment by Sharqosity** [comment]
Closed, check discord
