### ISSUE TITLE
Compiletime error

### ISSUE THREAD

**Issue by s0urc3d3v3l0pm3nt** [s0urc3d3v3l0pm3nt/whs_planner#76]
No ipass file, try logging in
@CalendarSaver0:0:0
java.lang.NullPointerException
@CalendarSaver1:0:0
java.lang.NullPointerException
@CalendarSaver2:0:0
java.lang.NullPointerException
@CalendarSaver3:0:0
java.lang.NullPointerException
CalendarSaver4:0:00:    
CalendarSaver4:0:01:    
CalendarSaver4:0:02:    Hello
CalendarSaver4:0:10:    
CalendarSaver4:0:11:    
CalendarSaver4:0:12:    Dank memes now
CalendarSaver4:0:20:   
CalendarSaver4:0:21:   
CalendarSaver4:0:22:   he
CalendarSaver4:0:30:  
CalendarSaver4:0:31:  
CalendarSaver4:0:32:  he
CalendarSaver4:0:40: 
CalendarSaver4:0:41: 
CalendarSaver4:0:42: h
@CalendarSaver4:0:5
java.lang.NullPointerException
@CalendarSaver5:0:0
java.lang.NullPointerException
@CalendarSaver6:0:0
java.lang.NullPointerException
@CalendarSaver7:0:0
java.lang.NullPointerException
@CalendarSaver8:0:0
java.lang.NullPointerException
@CalendarSaver9:0:0
java.lang.NullPointerException
@CalendarSaver10:0:0
java.lang.NullPointerException
@CalendarSaver11:0:0
java.lang.NullPointerException
@CalendarSaver12:0:0
java.lang.NullPointerException
@CalendarSaver13:0:0
java.lang.NullPointerException
@CalendarSaver14:0:0
java.lang.NullPointerException
@CalendarSaver15:0:0
java.lang.NullPointerException
@CalendarSaver16:0:0
java.lang.NullPointerException
@CalendarSaver17:0:0
java.lang.NullPointerException
@CalendarSaver18:0:0
java.lang.NullPointerException
@CalendarSaver19:0:0
java.lang.NullPointerException
@CalendarSaver20:0:0
java.lang.NullPointerException
@CalendarSaver21:0:0
java.lang.NullPointerException
@CalendarSaver22:0:0
java.lang.NullPointerException
@CalendarSaver23:0:0
java.lang.NullPointerException
@CalendarSaver24:0:0
java.lang.NullPointerException
@CalendarSaver25:0:0
java.lang.NullPointerException
@CalendarSaver26:0:0
java.lang.NullPointerException
@CalendarSaver27:0:0
java.lang.NullPointerException
@CalendarSaver28:0:0
java.lang.NullPointerException
@CalendarSaver29:0:0
java.lang.NullPointerException
@CalendarSaver30:0:0
java.lang.NullPointerException
Exception in Application start method

**Comment by Sharqosity** [comment]
Looks like there's a problem with CalendarSaver

**Comment by TBrient** [comment]
THANKS GEORGE

**Comment by TBrient** [comment]
😽

**Comment by Sharqosity** [comment]
Glad I could clear it up for you Tyler
