### ISSUE TITLE
Progress bar for get requests?

### ISSUE THREAD

**Issue by s0urc3d3v3l0pm3nt** [s0urc3d3v3l0pm3nt/whs_planner#80]
Having the day event pop up ~1 minute after signing in is a little clunky

**Comment by TBrient** [comment]
There are built in spinners, like the ones you can drag down to refresh on your phone. I would recommend using that. It's much more material than the progress bar.

**Comment by Sharqosity** [comment]
The application is literally frozen while it's loading... we tried to do this for news but it wouldn't work

**Comment by TBrient** [comment]
Can't you multithread it?
