### ISSUE TITLE
Prevent brute force iPass login

### ISSUE THREAD

**Issue by Sharqosity** [s0urc3d3v3l0pm3nt/whs_planner#90]
Just stop letting the user login for a while if he gets it wrong 100 times. Not sure if ipass already does this?

**Comment by Vrend** [comment]
ipass already blocks repeated attempts

**Comment by Sharqosity** [comment]
nice la

**Comment by Vrend** [comment]
I still can't login

**Comment by Vrend** [comment]
rip

**Comment by Sharqosity** [comment]
lmfao how many times did you get it wrong?

**Comment by Vrend** [comment]
like 50

i just spammed it and noticed the message changed

**Comment by Sharqosity** [comment]
You did this with the planner, and not the website right?

**Comment by Vrend** [comment]
nah the website

**Comment by Vrend** [comment]
it's fine

**Comment by Sharqosity** [comment]
Alright. Im gonna spam it in the client for science

**Comment by Sharqosity** [comment]
Ok. The api rejected me after 10 tries. Program doesn't launch again until ipass.key + Schedule.json are deleted, and even then it continues rejecting me. Issue officially closed
