### ISSUE TITLE
Code obfuscation

### ISSUE THREAD

**Issue by Sharqosity** [s0urc3d3v3l0pm3nt/whs_planner#91]
I think Andrew wanted this to be a thing. Should we look into this for the final compiled build?

**Comment by TBrient** [comment]
The way our code it written it is pretty much already obfuscated...

**Comment by Sharqosity** [comment]
LMAO what a roast @Vrend

**Comment by Vrend** [comment]
all part of the plan

op success

**Comment by Sharqosity** [comment]
We have a public git repo anyway, so theres no point really
