### ISSUE TITLE
3 dot menu top right

### ISSUE THREAD

**Issue by Sharqosity** [s0urc3d3v3l0pm3nt/whs_planner#94]
Not sure what node to use for it yet. But the menu should include:

- Refresh schedule (already exists)

- Logout of iPass (already exists)

- Send Feedback (it would link to a google form or something)

- About (version number, etc.)

- [ ] Bell 2 (This should be a feature we add later, a checkbox to change the timings)

3 dot icon: http://fontawesome.io/icon/ellipsis-v/

**Comment by TBrient** [comment]
I... did... it (John sucks cock) 😽
