### ISSUE TITLE
Schedule only shows quarter 1

### ISSUE THREAD

**Issue by Vrend** [s0urc3d3v3l0pm3nt/whs_planner#95]
This needs to be finished before release

**Comment by TBrient** [comment]
I'm john and I close stuff before I do it

**Comment by Sharqosity** [comment]
Is this even possible to fix? If not, well, iPass should be gone soon.

**Comment by s0urc3d3v3l0pm3nt** [comment]
I believe @Vrend has fixed this issue.  I don't know if he has pushed yet.  Until then this issue will be closed!
