### ISSUE TITLE
Make Calendar Year reset in July instead of January

### ISSUE THREAD

**Issue by Sharqosity** [s0urc3d3v3l0pm3nt/whs_planner#97]
currently the way it is, if it's dec and the end user wants to add an event to jan, he can't because clicking the next button will direct him to that same year's jan. 

I suggest having the year reset at July or August instead, because no one will be using the planner at that time.

**Comment by Sharqosity** [comment]
Of course, this isn't urgent because we have until next december to fix it before it becomes an issue.

**Comment by Vrend** [comment]
then again, you could just leave it because the school wipes the macbooks in the summer, so it should be like a new user when they use it again

**Comment by TBrient** [comment]
That's not the problem. The problem is that in December you can't add homework for January of next year. It will add it to January of that year. @Vrend

**Comment by Sharqosity** [comment]
Actually John is right, because even though it;s "technically" january of the same year, if you were currently in december, the data for the laptops got wiped in August anyway. So January would be clear.

**Comment by TBrient** [comment]
Oh okay, good point
