### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by Sharqosity** [s0urc3d3v3l0pm3nt/whs_planner#99]
is shit

**Comment by TBrient** [comment]
Thanks for the testing @TheCynosure

**Comment by TheCynosure** [comment]
I can't test schedule right now, but a large part of the performance issue comes from there being a ripple effect on JFXButtons. Problem is, I don't know if you can turn this off. @TBrient

**Comment by s0urc3d3v3l0pm3nt** [comment]
@thecynosure I would think that there is an underlying problem here.  ripple should not effect performance that severely
